### ISSUE TITLE
Pressed click

### ISSUE THREAD

**Issue by jquimera** [NigelOToole/priority-nav-scroller#1]
Good job. Is it possible to scroll items by clicking?

**Comment by NigelOToole** [comment]
Thanks, yes the items should scroll by clicking the arrow buttons. Are you getting an error?

**Comment by jquimera** [comment]
@NigelOToole I think I expressed myself poorly. It's not "clicking", this works fine. It is "pressed." something similar to what happens with scroll ...

**Comment by NigelOToole** [comment]
I think I understand, you mean it should scroll if you press down the button and hold it down. That is something I thought of but didn't have time to implement. I will try to get this feature into a future version.

**Comment by jquimera** [comment]
@NigelOToole Yes, that's it.
