### ISSUE TITLE
Standalone demo

### ISSUE THREAD

**Issue by adamjohnson** [NigelOToole/priority-nav-scroller#9]
Would love to see a standalone demo of Priority Nav Scroller. Preferably a demo that doesn't require a build process (so, [Codepen](https://codepen.io/) or [JSFiddle](https://jsfiddle.net/) vs [CodeSandbox](https://codesandbox.io/)). I'm having some trouble getting it to work sans build pipeline.

Thanks for putting this together. 👍

**Comment by NigelOToole** [comment]
Hi, you dont need to run the build process to use the plugin. The build process is just to run the demo website. The scripts and styles can just be copied from the src folder into your own project. You can also just run a simple server from the docs folder which is already complied. Hope that helps.

**Comment by adamjohnson** [comment]
Hey Nigel,

Thanks for getting back to me. I put together a [Codepen demo](https://codepen.io/adamjohnson/pen/vYXXjEZ) but couldn't get it working. 

I'm getting the following error as the demo is now:

```
SyntaxError: export declarations may only appear at top level of a module
```

When I try the UMD script, it says:

```
ReferenceError: PriorityNavScroller is not defined
```

Any chance you could take a look and let me know what I'm doing wrong? Would love to use this functionality for our sites. Thanks!

**Comment by NigelOToole** [comment]
Comment out the line "export default PriorityNavScroller;", you dont need it there since all the code is in one file.
